### ISSUE TITLE
missing binaries\textra-x86_64-pc-windows-msvc.exe

### ISSUE THREAD

**Issue by tikkanagi** [gsidhu/buzee-tauri#2]
trying to build this on Windows! 

error: failed to run custom build command for `buzee v0.2.0 (C:\Users\hello\code\buzee-tauri\src-tauri)`

Caused by:
  process didn't exit successfully: `C:\Users\hello\code\buzee-tauri\src-tauri\target\release\build\buzee-6826b410195de151\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-check-cfg=cfg(desktop)
  cargo:rustc-cfg=desktop
  cargo:rustc-check-cfg=cfg(mobile)
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_APP_NAME=buzee
  cargo:rustc-env=TAURI_ANDROID_PACKAGE_NAME_PREFIX=inc_buzilla
  cargo:rustc-check-cfg=cfg(dev)
  cargo:rustc-cfg=dev
  cargo:PERMISSION_FILES_PATH=C:\Users\hello\code\buzee-tauri\src-tauri\target\release\build\buzee-536b1193a71bf653\out\app-manifest\__app__-permission-files
  cargo:rerun-if-changed=capabilities
  cargo:rustc-env=TAURI_ENV_TARGET_TRIPLE=x86_64-pc-windows-msvc
  resource path `binaries\textra-x86_64-pc-windows-msvc.exe` doesn't exist
warning: build failed, waiting for other jobs to finish...
error: failed to compile `buzee v0.2.0 (C:\Users\hello\code\buzee-tauri\src-tauri)`, intermediate artifacts can be found at `C:\Users\hello\code\buzee-tauri\src-tauri\target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by gsidhu** [comment]
Building on Windows requires a few changes. Follow these steps:

1. Remove `drag = { path = "./crates/drag", version = "0.4.0", features = [ "serde" ] }` from [`Cargo.toml`](https://github.com/gsidhu/buzee-tauri/blob/main/src-tauri/Cargo.toml#L28C1-L28C77)
2. Comment out `crate::drag::start_drag,` from [`ipc.rs`](https://github.com/gsidhu/buzee-tauri/blob/main/src-tauri/src/ipc.rs#L506C7-L506C31)
3. Comment out `mod drag;` from [`main.rs`](https://github.com/gsidhu/buzee-tauri/blob/main/src-tauri/src/main.rs#L30)

Finally, replace `binaries/textra` with `binaries/winocr` in [`tauri.conf.json`](https://github.com/gsidhu/buzee-tauri/blob/main/src-tauri/tauri.conf.json#L38).

It should build fine with these changes.
